### ISSUE TITLE
Use a API to get synonyms

### ISSUE THREAD

**Issue by italux** [g-sponda/lxtm-generator#1]
[wordsapi](https://www.wordsapi.com/docs/) is free API tool that can be used for that like:

```
GET https://wordsapiv1.p.mashape.com/words/good/synonyms
```

> Words API is organized around RESTful principles. JSON will be returned in all responses from the API, including errors.
> 
> Access to the API is provided by [Rapid API](https://rapidapi.com/).

**Comment by g-sponda** [comment]
Close this issue.
This issue was opened and merge by this PR: https://github.com/g-sponda/lxtm-generator/pull/2
